#
# SemGeoWorkflows project
# Makefile
#

all:
	python semworkflows.py lcpath lights
	python semworkflows.py questions

l:
	python semworkflows.py lights

q:
	python semworkflows.py questions
	
clean:
	echo "TODO clean temp files"
