#comment:- Get possible inputs for workflows
SELECT DISTINCT ?wf ?op ?class ?firstin ?secondin 
WHERE{
{?wf wf:edge ?wfe. ?wfe rdf:subject ?op. ?op a ?class. 
?firstin a gis:Raster; ada:hasElement ?ine. ?ine ada:hasMeasure ?inm. ?inm  a gis:Existence; wf:of ?p. ?p a ada:Object.
FILTER(?class = gis:toLine)
}
UNION 
{?wf wf:edge ?wfe. ?wfe rdf:subject ?op. ?op a ?class.
?firstin a gis:Raster; ada:hasElement ?ine. ?ine ada:hasMeasure ?sinkm. ?sinkm a gis:Existence; wf:of ?object. ?object a ada:Object.
?secondin a gis:Raster; ada:hasElement ?ine2. ?ine2 ada:hasMeasure ?costm. ?costm wf:of ?field. ?field a gis:SField.
FILTER(?class = gis:CostDistance )
}
UNION {
?wf wf:edge ?wfe. ?wfe rdf:subject ?op. ?op a ?class .
?firstin a gis:Raster; ada:hasElement ?ine. ?ine ada:hasMeasure ?linkm. ?linkm a gis:Link.
?secondin a gis:Raster;  ada:hasElement ?ine2. ?ine2 ada:hasMeasure ?sourcem. ?sourcem a gis:Existence;wf:of ?object. ?object a ada:Object.
FILTER(?class = gis:CostPath )
}
UNION {
?wf wf:edge ?wfe. ?wfe rdf:subject ?op. ?op a ?class.
?firstin a gis:ObjectDataSet#; a gis:SpatialDataSet.
FILTER(?class = gis:EuclideanDistanceTool )
}
UNION {
?wf wf:edge ?wfe. ?wfe rdf:subject ?op. ?op a ?class.
?firstin a gis:RegionDataSet; ada:hasElement ?ine2. ?ine2 ada:hasMeasure ?m. ?m wf:of ?field. ?field a gis:SField.
FILTER NOT EXISTS{?firstin a gis:Raster}
FILTER(?class = gis:PolygontoRaster )
}
UNION {
?wf wf:edge ?wfe. ?wfe rdf:subject ?op. ?op a ?class.
?firstin a gis:PointDataSet.
FILTER(?class = gis:PointtoRaster )
}
UNION {
?wf wf:edge ?wfe. ?wfe rdf:subject ?op. ?op a ?class.
?firstin a gis:Raster; ada:hasElement ?ine2. ?ine2 ada:hasMeasure ?m. ?m wf:of ?field. ?field a gis:SField.
FILTER(?class = gis:LocalMapAlgebra )
}
}
ORDER BY ?op

#OPTIONAL {?ds a gis:FieldDataSet #FILTER(!isblank(?ofclass))
#}
