# Test Extract_tif1 dataset
SELECT DISTINCT ?el ?s ?whole ?ds 
WHERE{
	<http://geographicknowledge.de/WorkflowExamples#Extract_tif1> ada:hasElement ?el.
		#a ?type.
	?el ada:hasSupport ?s.
	#?el ada:hasMeasure ?m.
	optional {
		?s ada:partof ?whole.		 
	}
	optional {
		?ds ada:hasElement ?wel.
		?wel gis:hasAttribute ?whole.
	}		
	
}