#comment:- test for part of 
SELECT DISTINCT ?a ?b ?part ?whole
WHERE{
	?part ada:partof ?whole.
	?b ada:hasElement ?el.
	?el ada:hasAttribute ?part. 
	?a ada:hasElement ?el1.
	?el1 ada:hasAttribute ?whole. 
}