# Get all spatially aggregated results together with their (spatial) aggregation windows and their property source 
SELECT DISTINCT ?ds ?source ?window 
WHERE{
	?wf wf:result ?ds. 
	?ds ada:hasElement ?el.
	?el ada:hasSupport ?whole.
	?part ada:partOf ?whole. 
	?el2 ada:hasSupport ?part.
	?source ada:hasElement ?el2.
	?wf wf:source ?source .	
	
	?part ada:partOf ?windowr.	
	?el3 gis:hasAttribute ?windowr.
	?window ada:hasElement ?el3.	
	FILTER NOT EXISTS{?windowr owl:sameAs ?whole} #to exclude zones
	
}