# see all partof relations between supports and measures (b partof a)
SELECT DISTINCT ?b ?a ?part ?whole
WHERE{
	?part ada:partOf ?whole.
	?b ada:hasElement ?el.
	?el gis:hasAttribute ?part. 
	?a ada:hasElement ?el1.
	?el1 gis:hasAttribute ?whole. 
}